[workspace]

resolver = "2"

members = [
    "frostbow", "frostbow-sql", "frostbow-glue"
]

[workspace.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
clap = { version = "4.5", features = ["derive"] }
datafusion = "53"
datafusion-cli = { version = "53" }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
object_store = { version = "0.13", features = ["aws", "gcp"] }
iceberg-rust = { git = "https://github.com/JanKaul/iceberg-rust.git", branch = "main" }
datafusion_iceberg = { git = "https://github.com/JanKaul/iceberg-rust.git", branch = "main" }
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[patch.crates-io]
arrow         = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
arrow-arith   = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
arrow-array   = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
arrow-buffer  = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
arrow-cast    = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
arrow-csv     = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
arrow-data    = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
arrow-ipc     = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
arrow-json    = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
arrow-ord     = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
arrow-row     = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
arrow-schema  = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
arrow-select  = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
arrow-string  = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }
parquet       = { git = "https://github.com/Embucket/arrow-rs.git", branch = "hll-v58.2.0" }

